
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-07
owner: ucsb-cs156-s25
repo_name: team01-s25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwMzMwODU2","is_bot":false,"login":"acdamstedt","name":"Annika Damstedt"},"headRefName":"Annika-HelpRequest-create-controller","number":56,"title":"Create HelpRequestController, add GET (index) and POST (create) ","url":"https://github.com/ucsb-cs156-s25/team01-s25-07/pull/56"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"Steven-put-for-RecRequest-table","number":55,"title":"Steven - PUT for rec request table","url":"https://github.com/ucsb-cs156-s25/team01-s25-07/pull/55"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"Steven-RecommendationRequest-get-by-id","number":54,"title":"Steven - add get by id for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-07/pull/54"}]
