
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-07
owner: ucsb-cs156-s25
repo_name: team01-s25-07
pull_requests: [{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"Forrest-create-item-controller","number":45,"title":"Created UCSBDiningCommonsMenuItem Controller and added GET and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-07/pull/45"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"shelly-articles","number":43,"title":"sz-create db for articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-07/pull/43"}]
